### ISSUE TITLE
[Wishlist] Ability to download / stream music

### ISSUE THREAD

**Issue by Yenthe666** [nicolasmartinelli/oomusic#3]
Hi @nicolasmartinelli,

First of all, great work, I was amazed to see this! 👍
I was wondering if you could add support to download songs / livestream them from somewhere? I like the concept would it would be even better if you can search for songs in the Odoo and listen them live.
A bit of the same concept as Spotify.
Any chance that could be build? 💎 

Regards,
Yenthe

**Comment by nicolasmartinelli** [comment]
Hi,

Thanks for the support.

I'm not sure I understand your question. The module is actually able to stream the music in order to play it in the Odoo interface. You can try the demo server: http://demo.koozic.net:8069/web/login?db=koozic&login=demo&key=demo

To download a file, an hidden feature exists: http://demo.koozic.net:8069/oomusic/down/1 (works only if you are logged in). I'm still wondering whether this is really useful to add...

**Comment by Yenthe666** [comment]
Hi @nicolasmartinelli,

Thanks for your answer.
I actually mean that at this point you need to have the mp3 files on your server. It would be great if you didn't have to physically put them in a folder but if you could stream them from somewhere or that they automatically get downloaded on the server.
By doing so you can basically create all the playlists you'd like, from whatever songs you'd like.

Regards,
Yenthe

**Comment by nicolasmartinelli** [comment]
Thanks for the clarification.

If it's about sharing files between the Odoo server and some external source, I think there are already enough alternatives than can handle this at the operating system level. NFS, Samba, SSHFS, WebDAV, or even FTP are among the most popular ones. Once a local mount point has been created, your Odoo server will access the files in the same way it would do it with local files.

The thing is, it's not really about what the Odoo server supports, but more what the external source accepts. It's practically impossible to build an extension that would be able to connect to any kind of possible source.
